name: Deploy to Production

on:
  push:
    branches: [main]
    paths:
      - index.html
      - 'src/**'
      - pnpm-lock.yaml
      - package.json

jobs:
  unit-test:
    uses: tzuyi0817/workflows/.github/workflows/test.yml@v1
    with:
      test: pnpm test:unit
      env-list: VITE_CDN_API_URL=${{ vars.VITE_CDN_API_URL }}

  deploy:
    needs: unit-test
    uses: tzuyi0817/workflows/.github/workflows/deploy-vercel.yml@v1
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}

    with:
      environment: Production
      prod: true
